<template>
  <h2>Button.vue</h2>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>
  <p>button内容</p>

</template>

<script lang="ts">
  export default {
    name: 'Button',
  };
</script>

<style lang="scss" scoped>

</style>