<template>
  <h2>Dialog.vue</h2>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
  <p>dialog内容</p>
</template>

<script lang="ts">
  export default {
    name: 'Dialog',
  };
</script>

<style lang="scss" scoped>

</style>