<template>
  <h2>Tabs.vue</h2>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
  <p>tabs内容</p>
</template>

<script lang="ts">
  export default {
    name: 'Tabs',
  };
</script>

<style lang="scss" scoped>

</style>